version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
      - ./static:/app/static  # Ensure you have a volume for static files
      - ./staticfiles:/app/staticfiles  # Ensure you have a volume for static files
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:17-alpine
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static  # Ensure you have a volume for static files
      - ./media:/app/media    # Ensure you have a volume for media files
      - ./staticfiles:/app/staticfiles  # Ensure you have a volume for static files
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge
