# Generated by Django 5.0.7 on 2024-10-01 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255, verbose_name='Payment Method Name')),
                ('method_type', models.CharField(choices=[('bank_account', 'Bank Account')], max_length=50, verbose_name='Payment Type')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
                'unique_together': {('user', 'method_name')},
            },
        ),
        migrations.CreateModel(
            name='FundsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('source_details', models.TextField(blank=True, null=True, verbose_name='Source Details')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_transactions', to='expense_tracker.paymentmethod', verbose_name='Payment Method')),
            ],
        ),
    ]
