# Generated by Django 5.0.7 on 2024-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_expense_created_at_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('credit_card', 'Credit Card'), ('digital_wallet', 'Digital Wallet'), ('other', 'Other')], max_length=50, verbose_name='Payment Type'),
        ),
    ]
