# Generated by Django 5.0.7 on 2024-10-03 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_paymentmethod_method_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundstransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
    ]
