# Generated by Django 5.0.7 on 2024-10-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0005_fundstransaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundstransaction',
            old_name='date',
            new_name='funds_date',
        ),
    ]
