# Generated by Django 5.0.7 on 2024-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0006_rename_date_fundstransaction_funds_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('groceries', 'Groceries'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('shopping', 'Shopping'), ('subscriptions', 'Subscriptions'), ('education', 'Education'), ('savings', 'Savings'), ('investments', 'Investments'), ('debts', 'Debts'), ('travel', 'Travel'), ('gifts', 'Gifts'), ('charity', 'Charity'), ('taxes', 'Taxes'), ('maintenance', 'Maintenance'), ('pets', 'Pets'), ('childcare', 'Childcare'), ('personal_care', 'Personal Care'), ('other', 'Other')], max_length=50, verbose_name='Category'),
        ),
    ]
